---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master-svc
  namespace: monitoring
  labels:
    app: elasticsearch-master
spec:
  selector:
    app: elasticsearch-master
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport
---
#Coordinating service
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-svc
  namespace: monitoring
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport 
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-data-svc
  namespace: monitoring
  labels:
    app: elasticsearch-data
spec:
  selector:
    app: elasticsearch-data
  type: ClusterIP
  ports:
    - port: 9200
      name: http
    - port: 9300
      name: transport             
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  namespace: monitoring
spec:
  serviceName: elasticsearch-master
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch-master
  template:
    metadata:
      labels:
        app: elasticsearch-master
    spec:
      affinity: 
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch-master
                topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch-master
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        resources:
            limits:
              cpu: 1000m
              memory: 1G
            requests:
              cpu: 100m
              memory: 512m
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
        readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
        volumeMounts:
        - name: data-master
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "elasticsearch-master-svc"
          - name: cluster.initial_master_nodes
            value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          - name: xpack.security.enabled
            value: "false"
          - name: xpack.monitoring.enabled
            value: "true"
          - name: xpack.monitoring.collection.enabled
            value: "true"
          - name: node.master
            value: "true"
          - name: node.voting_only
            value: "false"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "true"
          - name: node.ml
            value: "false"
          - name: cluster.remote.connect
            value: "false"
      initContainers:
      - name: fix-ownership
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data-master
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true              
  volumeClaimTemplates:
  - metadata:
      name: data-master
      labels:
        app: elasticsearch-master
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
---
#Coordinating set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: monitoring
spec:
  serviceName: elasticsearch
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      affinity: 
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch
                topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        resources:
            limits:
              cpu: 1000m
              memory: 1G
            requests:
              cpu: 100m
              memory: 512m
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
        readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
        volumeMounts:
        - name: data-coordinating
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "elasticsearch-master-svc"
          - name: cluster.initial_master_nodes
            value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          - name: xpack.security.enabled
            value: "false"
          - name: xpack.monitoring.enabled
            value: "true"
          - name: xpack.monitoring.collection.enabled
            value: "true"
          - name: node.master
            value: "false"
          - name: node.voting_only
            value: "false"
          - name: node.data
            value: "false"
          - name: node.ingest
            value: "false"
          - name: node.ml
            value: "false"
          - name: cluster.remote.connect
            value: "false"
      initContainers:
      - name: fix-ownership
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data-coordinating
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true              
  volumeClaimTemplates:
  - metadata:
      name: data-coordinating
      labels:
        app: elasticsearch
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: monitoring
spec:
  serviceName: elasticsearch-data
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: elasticsearch-data
  template:
    metadata:
      labels:
        app: elasticsearch-data
    spec:
      affinity: 
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - elasticsearch-data
                topologyKey: kubernetes.io/hostname
      containers:
      - name: elasticsearch-data
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        resources:
            limits:
              cpu: 1000m
              memory: 2G
            requests:
              cpu: 100m
              memory: 1G
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        livenessProbe:
            tcpSocket:
              port: 9300
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
        readinessProbe:
            httpGet:
              scheme: HTTP
              path: /_cluster/health?local=true
              port: 9200
            initialDelaySeconds: 15
            timeoutSeconds: 10
            failureThreshold: 10
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
        env:
          - name: cluster.name
            value: k8s-logs
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "elasticsearch-master-svc"
          - name: cluster.initial_master_nodes
            value: "elasticsearch-master-0,elasticsearch-master-1,elasticsearch-master-2"
          - name: ES_JAVA_OPTS
            value: "-Xms256m -Xmx256m"
          - name: xpack.security.enabled
            value: "false"
          - name: xpack.monitoring.enabled
            value: "true"
          - name: xpack.monitoring.collection.enabled
            value: "true"
          - name: node.master
            value: "false"
          - name: node.voting_only
            value: "false"
          - name: node.data
            value: "true"
          - name: node.ingest
            value: "false"
          - name: node.ml
            value: "false"
          - name: cluster.remote.connect
            value: "false"
      initContainers:
      - name: fix-ownership
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /usr/share/elasticsearch/data"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true              
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: elasticsearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 500Gi