apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: elastic-system
  labels:
    app: elasticsearch
spec:
  selector:
    app: elasticsearch
  clusterIP: None
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: inter-node