apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - setup.yml
  - elasticsearch.yml
  - kibana.yml
  - logstash.yml
  - beats/metricbeat.yml
  - beats/auditbeat.yml
  - beats/filebeat.yml