apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: elk-stack
  labels:
    app: logstash
spec:
  type: ClusterIP
  selector:
    app: logstash
  ports:
  - name: http
    port: 5044
    targetPort: 5044
  - name: api
    port: 9600
    targetPort: 9600
---
apiVersion: v1               
kind: Service                
metadata:                    
  name: logstash-lb        
  namespace: elk-stack
  labels:                    
    app: logstash
spec:                        
  type: LoadBalancer         
  selector:                  
    app: logstash
  ports:                     
  - name: http               
    port: 5044               
    protocol: TCP
  - name: api               
    port: 9600               
    protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash
  namespace: elk-stack
  labels:
    app: logstash
data:
  logstash.yml: |-
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  pipeline.conf: |-
    input {
      beats {
        port => 5044
      }
    }
    output {
      elasticsearch {
        hosts => ['${ELASTICSEARCH_HOST:elasticsearch-service}:${ELASTICSEARCH_PORT:9200}']
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: elk-stack
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:7.5.0
        resources:
            limits:
              memory: "256M"
              cpu: 1000m
            requests:
              memory: "128M"
              cpu: 100m
        env:
          - name:  ELASTICSEARCH_HOST
            value: "elasticsearch-service"
          - name:  ELASTICSEARCH_PORT
            value: "9200"
        ports:
        - containerPort: 5044
          name: http
          protocol: TCP
        - containerPort: 9600
          name: api
          protocol: TCP
        livenessProbe:
            tcpSocket:
              port: 5044
            initialDelaySeconds: 20
            periodSeconds: 10
        volumeMounts:
          - name: logstash-settings-config-volume
            mountPath: /usr/share/logstash/config
          - name: logstash-pipeline-config-volume
            mountPath: /usr/share/logstash/pipeline
      volumes:
      - name: logstash-settings-config-volume
        configMap:
          name: logstash
          items:
            - key: logstash.yml
              path: logstash.yml
      - name: logstash-pipeline-config-volume
        configMap:
          name: logstash
          items:
            - key: pipeline.conf
              path: pipeline.conf