apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  namespace: elastic-system
  labels:
    app: logstash
    version: "1.0"
    environment: logging
spec:
  type: ClusterIP
  selector:
    app: logstash
    version: "1.0"
    environment: logging
  ports:
  - port: 5044
    targetPort: 5044