apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: monitoring
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: pod-quota
#   namespace: monitoring
# spec:
#   hard:
#     requests.cpu: "7"
#     requests.memory: 10Gi
#     limits.cpu: "10"
#     limits.memory: 20Gi