apiVersion: v1
kind: Namespace
metadata:
  name: elk-stack
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ssd
  namespace: elk-stack
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd