---
apiVersion: v1
kind: ConfigMap
metadata:
  name: journalbeat-config
  namespace: kube-system
  labels:
    k8s-app: journalbeat
data:
  journalbeat.yml: |-
    journalbeat.inputs:
    - paths: ["/var/log/journal"]
      seek: cursor

    processors:
    - add_cloud_metadata: ~
    - add_kubernetes_metadata:
        in_cluster: true
        default_indexers.enabled: false
        default_matchers.enabled: false
        indexers:
          - container:
        matchers:
          - fields:
              lookup_fields: ["container.id"]

    output.logstash.hosts: 'logstash-svc.monitoring.svc.cluster.local:5044'
    # setup.kibana.host: "http://kibana-svc.monitoring.svc.cluster.local:5601"
    # setup.dashboards.enabled: true
    # setup.dashboards.index: "journalbeat-*"
#    output.elasticsearch.hosts: ['${ELASTICSEARCH_HOST:elasticsearch-svc.monitoring.svc.cluster.local}:${ELASTICSEARCH_PORT:9200}']

    
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: kube-system
  labels:
    k8s-app: journalbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: journalbeat
    spec:
      serviceAccountName: journalbeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: journalbeat
        image: docker.elastic.co/beats/journalbeat:7.6.0
        args: [
          "-c", "/etc/journalbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-svc.monitoring.svc.cluster.local
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/journalbeat.yml
          readOnly: true
          subPath: journalbeat.yml
        - name: data
          mountPath: /usr/share/journalbeat/data
        - name: varlogjournal
          mountPath: /var/log/journal
          readOnly: true
        - name: machineid
          mountPath: /etc/machineid
          readOnly: true
        - name: systemd
          mountPath: /run/systemd
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: journalbeat-config
      - name: varlogjournal
        hostPath:
          path: /var/log/journal
      - name: machineid
        hostPath:
          path: /etc/machine-id
      - name: systemd
        hostPath:
          path: /run/systemd
      - name: data
        emptyDir: {}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: journalbeat
subjects:
- kind: ServiceAccount
  name: journalbeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: journalbeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: journalbeat
  labels:
    k8s-app: journalbeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: journalbeat
  namespace: kube-system
  labels:
    k8s-app: journalbeat